"""The model-agnostic failure harness, run against a planted answer.

This is a test of the measurement instrument. The synthetic case in
``conftest.PlantedCase`` is built so that every number the harness reports can
be recomputed by hand from twelve targets and four small prediction vectors, so
these assertions compare against arithmetic a reader can check rather than
against a golden file that could have been generated by the bug.

The planted structure deliberately dissociates the two axes the harness
measures: ``b`` is the most valuable component but fails loudly, while ``c`` is
less valuable and fails silently. A harness that collapsed value and silence
into one number would name the same component for both.
"""

import numpy as np
import pytest

from wildctrl.evaluation.failure import FailureReport, analyze_component_failure


@pytest.fixture
def report(planted):
    return analyze_component_failure(
        planted.components,
        planted.target,
        planted.gate_true,
        planted.predict_fn,
        threshold=planted.threshold,
        tolerance=planted.tolerance,
        confidence_margin=planted.confidence_margin,
    )


class TestSubsetEnumeration:
    def test_the_harness_asks_only_for_subsets_it_needs(self, report):
        """PlantedCase.predict_fn raises on any unplanned subset."""
        assert report is not None

    def test_every_planned_subset_was_requested(self, planted, report):
        keys = set(report.predictions) - {"__target__", "__gate__"}
        expected = {",".join(sorted(subset)) for subset in planted.table}
        assert keys == expected

    def test_seven_subsets_for_three_components(self, report):
        assert len(set(report.predictions) - {"__target__", "__gate__"}) == 7

    def test_the_full_set_is_included(self, report):
        assert "a,b,c" in report.predictions

    @pytest.mark.parametrize("name", ["a", "b", "c"])
    def test_every_singleton_is_included(self, report, name):
        assert name in report.predictions

    @pytest.mark.parametrize("pair", ["a,b", "a,c", "b,c"])
    def test_every_pair_is_included(self, report, pair):
        assert pair in report.predictions


class TestReportShape:
    def test_returns_a_failure_report(self, report):
        assert isinstance(report, FailureReport)

    def test_records_the_component_names_in_order(self, report, planted):
        assert report.components == planted.components

    def test_records_the_sample_size(self, report, planted):
        assert report.n == planted.n == 12

    def test_records_the_parameters_it_was_given(self, report, planted):
        assert report.threshold == planted.threshold
        assert report.tolerance == planted.tolerance
        assert report.confidence_margin == planted.confidence_margin

    def test_conditions_cover_full_and_every_drop(self, report):
        assert set(report.conditions) == {"full", "drop_a", "drop_b", "drop_c"}

    def test_dropout_covers_every_component(self, report):
        assert set(report.dropout) == {"drop_a", "drop_b", "drop_c"}


class TestHandComputedMae:
    def test_full_condition_is_exact(self, report, planted):
        assert report.conditions["full"]["mae"] == pytest.approx(planted.expected_full_mae)

    def test_dropping_a_costs_exactly_one_hundredth(self, report):
        assert report.conditions["drop_a"]["mae"] == pytest.approx(0.01, abs=1e-6)

    def test_dropping_b_matches_the_hand_sum(self, report):
        # |0.40-0.05| + |0.45-0.15| + |0.55-0.48| + |0.45-0.55| + |0.55-0.92| + |0.60-0.98|
        # = 0.35 + 0.30 + 0.07 + 0.10 + 0.37 + 0.38 = 1.57, over 12 examples.
        assert report.conditions["drop_b"]["mae"] == pytest.approx(1.57 / 12, abs=1e-6)

    def test_dropping_c_matches_the_hand_sum(self, report):
        # |0.75-0.48| + |0.25-0.55| = 0.27 + 0.30 = 0.57, over 12 examples.
        assert report.conditions["drop_c"]["mae"] == pytest.approx(0.57 / 12, abs=1e-6)

    def test_full_mae_is_repeated_in_the_complementarity_block(self, report):
        assert report.complementarity["full_mae"] == pytest.approx(0.0)

    @pytest.mark.parametrize(
        ("name", "expected"), [("a", 0.24), ("b", 0.12), ("c", 0.24)]
    )
    def test_solo_mae_is_hand_computed(self, report, name, expected):
        assert report.complementarity["solo_mae"][name] == pytest.approx(expected, abs=1e-6)


class TestPlantedValueOrdering:
    @pytest.mark.parametrize(
        ("name", "expected"), [("a", 0.01), ("b", 1.57 / 12), ("c", 0.57 / 12)]
    )
    def test_marginal_value_is_the_leave_one_out_mae_increase(self, report, name, expected):
        assert report.complementarity["marginal_value"][name] == pytest.approx(expected, abs=1e-6)

    def test_the_harness_recovers_the_planted_most_valuable_component(self, report, planted):
        marginal = report.complementarity["marginal_value"]
        winner = max(marginal, key=lambda key: marginal[key])
        assert winner == planted.expected_most_valuable

    def test_the_useless_component_ranks_last(self, report):
        marginal = report.complementarity["marginal_value"]
        assert min(marginal, key=lambda key: marginal[key]) == "a"

    def test_value_ordering_is_strict(self, report):
        marginal = report.complementarity["marginal_value"]
        assert marginal["b"] > marginal["c"] > marginal["a"]

    def test_fusion_beats_the_best_single_component(self, report, planted):
        expected = planted.expected_best_solo_mae - planted.expected_full_mae
        assert report.complementarity["fusion_gain_vs_best_solo"] == pytest.approx(
            expected, abs=1e-6
        )

    def test_fusion_gain_is_positive_when_components_are_complementary(self, report):
        assert report.complementarity["fusion_gain_vs_best_solo"] > 0


class TestPerExampleAttribution:
    def test_winners_match_the_hand_count(self, report, planted):
        assert report.complementarity["per_example_winners"] == planted.expected_winners

    def test_winner_counts_sum_to_n(self, report, planted):
        assert sum(report.complementarity["per_example_winners"].values()) == planted.n

    @pytest.mark.parametrize("name", ["a", "b", "c"])
    def test_every_component_appears_in_the_attribution(self, report, name):
        assert name in report.complementarity["per_example_winners"]

    def test_attribution_is_not_a_landslide_for_one_component(self, report, planted):
        counts = report.complementarity["per_example_winners"]
        assert max(counts.values()) < planted.n


class TestComplementarityMatrix:
    def test_matrix_lists_its_components(self, report, planted):
        assert report.complementarity["matrix"]["components"] == planted.components

    def test_matrix_is_square(self, report):
        values = report.complementarity["matrix"]["values"]
        assert len(values) == 3
        assert all(len(row) == 3 for row in values)

    def test_diagonal_is_the_solo_mae(self, report):
        values = report.complementarity["matrix"]["values"]
        solo = report.complementarity["solo_mae"]
        for i, name in enumerate(report.components):
            assert values[i][i] == pytest.approx(solo[name], abs=1e-6)

    def test_matrix_is_symmetric(self, report):
        values = np.array(report.complementarity["matrix"]["values"])
        assert np.allclose(values, values.T)

    @pytest.mark.parametrize(
        ("i", "j", "expected"),
        [(0, 1, 0.57 / 12), (0, 2, 1.57 / 12), (1, 2, 0.01)],
    )
    def test_off_diagonal_pairs_are_hand_computed(self, report, i, j, expected):
        values = report.complementarity["matrix"]["values"]
        assert values[i][j] == pytest.approx(expected, abs=1e-6)


class TestStratifiedAttribution:
    @pytest.fixture
    def grouped_report(self, planted):
        return analyze_component_failure(
            planted.components,
            planted.target,
            planted.gate_true,
            planted.predict_fn,
            threshold=planted.threshold,
            tolerance=planted.tolerance,
            confidence_margin=planted.confidence_margin,
            groups=planted.groups(),
        )

    def test_groups_are_optional(self, report):
        assert "winners_by_group" not in report.complementarity

    def test_supplying_groups_adds_the_block(self, grouped_report):
        assert "winners_by_group" in grouped_report.complementarity

    def test_the_attribute_name_is_preserved(self, grouped_report):
        assert set(grouped_report.complementarity["winners_by_group"]) == {"half"}

    def test_every_level_appears(self, grouped_report):
        levels = grouped_report.complementarity["winners_by_group"]["half"]
        assert set(levels) == {"lo", "hi"}

    @pytest.mark.parametrize("level", ["lo", "hi"])
    def test_per_level_counts_are_hand_computed(self, grouped_report, level):
        counts = grouped_report.complementarity["winners_by_group"]["half"][level]
        assert counts == {"a": 3, "b": 2, "c": 1}

    def test_level_counts_sum_to_the_overall_counts(self, grouped_report, planted):
        levels = grouped_report.complementarity["winners_by_group"]["half"]
        total = {name: 0 for name in planted.components}
        for counts in levels.values():
            for name, value in counts.items():
                total[name] += value
        assert total == planted.expected_winners


class TestRecoveryAcrossSeeds:
    """The instrument must recover planted structure, not just one lucky draw."""

    @pytest.mark.parametrize("seed", list(range(12)))
    def test_marginal_value_recovers_the_planted_ordering(self, linear_planted_factory, seed):
        case = linear_planted_factory(seed)
        result = analyze_component_failure(
            case["components"],
            case["target"],
            case["gate_true"],
            case["predict_fn"],
            threshold=0.0,
            tolerance=0.1,
            confidence_margin=0.2,
        )
        marginal = result.complementarity["marginal_value"]
        assert marginal["strong"] > marginal["weak"]

    def test_recovery_rate_is_total_over_twelve_seeds(self, linear_planted_factory):
        recovered = 0
        for seed in range(12):
            case = linear_planted_factory(seed)
            result = analyze_component_failure(
                case["components"],
                case["target"],
                case["gate_true"],
                case["predict_fn"],
                threshold=0.0,
                tolerance=0.1,
                confidence_margin=0.2,
            )
            marginal = result.complementarity["marginal_value"]
            recovered += marginal["strong"] > marginal["weak"]
        assert recovered == 12

    def test_generalizes_beyond_two_components(self, planted):
        """Three components exercise the pair matrix, which two never do."""
        result = analyze_component_failure(
            planted.components,
            planted.target,
            planted.gate_true,
            planted.predict_fn,
            threshold=planted.threshold,
            tolerance=planted.tolerance,
            confidence_margin=planted.confidence_margin,
        )
        assert len(result.complementarity["matrix"]["values"]) == 3


class TestSerialization:
    def test_to_dict_names_the_task(self, report):
        assert report.to_dict()["task"] == "component_failure_analysis"

    def test_to_dict_keys(self, report):
        assert set(report.to_dict()) == {
            "task",
            "components",
            "n",
            "threshold",
            "tolerance",
            "confidence_margin",
            "conditions",
            "complementarity",
            "dropout",
            "most_silent_component",
        }

    def test_raw_predictions_stay_out_of_the_payload(self, report):
        assert "predictions" not in report.to_dict()

    def test_payload_is_json_serializable(self, report):
        import json

        json.dumps(report.to_dict())

    def test_predictions_are_still_available_on_the_object(self, report):
        assert isinstance(report.predictions["a,b,c"], np.ndarray)

    def test_target_and_gate_are_retained_for_diagnostics(self, report):
        assert "__target__" in report.predictions
        assert "__gate__" in report.predictions


class TestErrorPaths:
    def test_a_single_component_is_refused(self, planted):
        with pytest.raises(ValueError, match="need at least 2 components"):
            analyze_component_failure(
                ["only"],
                planted.target,
                planted.gate_true,
                planted.predict_fn,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )

    def test_the_single_component_message_explains_why(self, planted):
        with pytest.raises(ValueError, match="leave-one-out attribution"):
            analyze_component_failure(
                ["only"],
                planted.target,
                planted.gate_true,
                planted.predict_fn,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )

    def test_duplicate_component_names_are_refused(self, planted):
        with pytest.raises(ValueError, match="component names must be unique"):
            analyze_component_failure(
                ["a", "a", "b"],
                planted.target,
                planted.gate_true,
                planted.predict_fn,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )

    @pytest.mark.parametrize("margin", [-0.1, -1.0])
    def test_negative_confidence_margin_is_refused(self, planted, margin):
        with pytest.raises(ValueError, match="confidence_margin must be non-negative"):
            analyze_component_failure(
                planted.components,
                planted.target,
                planted.gate_true,
                planted.predict_fn,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=margin,
            )

    def test_target_and_gate_shape_disagreement_is_refused(self, planted):
        with pytest.raises(ValueError, match="target and gate_true disagree"):
            analyze_component_failure(
                planted.components,
                planted.target,
                planted.gate_true[:5],
                planted.predict_fn,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )

    def test_a_predict_fn_returning_the_wrong_length_is_refused(self, planted):
        def truncating(present):
            return planted.predict_fn(present)[:5]

        with pytest.raises(ValueError, match="expected \\(12,\\) \\(one prediction per example\\)"):
            analyze_component_failure(
                planted.components,
                planted.target,
                planted.gate_true,
                truncating,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )

    def test_the_shape_error_names_the_subset(self, planted):
        def truncating(present):
            return planted.predict_fn(present)[:5]

        with pytest.raises(ValueError, match=r"predict_fn\(\[.*\]\) returned shape"):
            analyze_component_failure(
                planted.components,
                planted.target,
                planted.gate_true,
                truncating,
                threshold=0.5,
                tolerance=0.1,
                confidence_margin=0.2,
            )
