"""Render paper-grade figures from the aggregate payload.

Matplotlib defaults are for looking at data, not for printing it. This script
sets the rcParams that matter for a submission and would otherwise be
rediscovered the night before a deadline: a serif family matching a LaTeX body,
``pdf.fonttype: 42`` and ``svg.fonttype: none`` so text stays selectable and
editable rather than being converted to outlines, a colourblind-safe palette,
and a figure sized to the column it will sit in.

Every figure is written in all three configured formats from one call, and a
caption is generated from the plotted numbers. A hand-written caption stops
matching the figure the second time the figure is regenerated.

When there is nothing to plot, a labelled placeholder is written rather than an
empty axis, so a missing result looks missing instead of looking like zero.

Usage:
    python scripts/make_figures.py
    python scripts/make_figures.py --metric silent_rate --group-by task
    python scripts/make_figures.py --in results/results.json --out-dir results/figures
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Okabe-Ito: distinguishable under the common forms of colour vision deficiency
# and in greyscale print.
PALETTE = ["#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#F0E442"]

RC_PARAMS = {
    "font.family": "serif",
    "font.size": 9,
    "axes.labelsize": 9,
    "axes.titlesize": 9,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "legend.fontsize": 8,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linewidth": 0.5,
    "figure.dpi": 150,
    "savefig.bbox": "tight",
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "svg.fonttype": "none",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate publication-grade result figures.")
    parser.add_argument("--in", dest="source", default="results/results.json")
    parser.add_argument("--out-dir", default="results/figures")
    parser.add_argument("--name", default="main_result", help="Base filename, without extension.")
    parser.add_argument("--metric", default=None, help="Metric to plot. Defaults to the first.")
    parser.add_argument("--group-by", default="task", help="Provenance column used on the x axis.")
    parser.add_argument("--formats", nargs="*", default=["pdf", "svg", "png"])
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--width", type=float, default=6.6)
    parser.add_argument("--height", type=float, default=2.6)
    parser.add_argument("--ylabel", default=None)
    return parser


def group_values(rows: list[dict], group_by: str, metric: str) -> dict[str, list[float]]:
    """Metric values per group, in first-seen group order."""
    grouped: dict[str, list[float]] = {}
    for row in rows:
        value = row.get("metrics", {}).get(metric)
        if value is None:
            continue
        grouped.setdefault(str(row.get(group_by, "?")), []).append(float(value))
    return grouped


def summarize(grouped: dict[str, list[float]]) -> list[tuple[str, float, float, int]]:
    """``(group, mean, stdev, n)`` per group; stdev is 0 for a single observation."""
    return [
        (
            name,
            statistics.fmean(values),
            statistics.stdev(values) if len(values) > 1 else 0.0,
            len(values),
        )
        for name, values in grouped.items()
    ]


def write_caption(path: Path, metric: str, stats: list[tuple[str, float, float, int]]) -> Path:
    """Generate the caption text from the plotted numbers.

    Includes the interval disclaimer explicitly: a bar with no visible error bar
    because a group has one seed is not a precise measurement, and the caption
    has to say so rather than letting the figure imply otherwise.
    """
    if not stats:
        text = (
            f"Placeholder for {metric.replace('_', ' ')}. No measured results exist yet, so "
            "no numbers are plotted. This figure is regenerated by "
            "scripts/make_figures.py once runs have been recorded."
        )
    else:
        best = max(stats, key=lambda item: item[1])
        worst = min(stats, key=lambda item: item[1])
        single = [name for name, _mean, _sd, count in stats if count < 2]
        text = (
            f"{metric.replace('_', ' ').capitalize()} by "
            f"{len(stats)} condition{'s' if len(stats) != 1 else ''}. "
            f"Highest: {best[0]} at {best[1]:.3f}"
            + (f" (sd {best[2]:.3f}, n={best[3]})" if best[3] > 1 else f" (n={best[3]})")
            + f"; lowest: {worst[0]} at {worst[1]:.3f}. "
            "Panel (a) shows the group means with one standard deviation across seeds; "
            "panel (b) shows the individual per-seed values behind each mean."
        )
        if single:
            text += (
                f" No interval is shown for {', '.join(single)}: "
                "only one seed has been run, so the spread is unknown."
            )
    path.write_text(text + "\n", encoding="utf-8")
    return path


def render(stats, grouped, metric: str, args: argparse.Namespace):
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(RC_PARAMS)
    fig, axes = plt.subplots(1, 2, figsize=(args.width, args.height))
    left, right = axes
    ylabel = args.ylabel or metric.replace("_", " ")

    if not stats:
        for axis, label in zip(axes, ("(a)", "(b)")):
            axis.text(
                0.5, 0.5, "no measured results yet",
                ha="center", va="center", transform=axis.transAxes, color="#666666",
            )
            axis.set_xticks([])
            axis.set_yticks([])
            axis.set_title(label, loc="left")
    else:
        names = [item[0] for item in stats]
        means = [item[1] for item in stats]
        errors = [item[2] for item in stats]
        colors = [PALETTE[index % len(PALETTE)] for index in range(len(stats))]

        left.bar(names, means, yerr=errors, capsize=3, color=colors, edgecolor="none")
        left.set_ylabel(ylabel)
        left.set_title("(a)", loc="left")
        left.tick_params(axis="x", rotation=30)

        for index, name in enumerate(names):
            values = grouped[name]
            right.scatter(
                [index] * len(values), values, s=14,
                color=PALETTE[index % len(PALETTE)], alpha=0.85,
            )
        right.set_xticks(range(len(names)))
        right.set_xticklabels(names, rotation=30)
        right.set_ylabel(ylabel)
        right.set_title("(b)", loc="left")

    fig.tight_layout()
    return fig


def main(argv: list[str] | None = None) -> int:
    """Write the main result figure in every configured format, plus its caption."""
    args = build_parser().parse_args(argv)

    source = Path(args.source) if Path(args.source).is_absolute() else REPO_ROOT / args.source
    if not source.is_file():
        print(f"{source} does not exist. Run `python scripts/aggregate_results.py` first.")
        return 2

    payload = json.loads(source.read_text(encoding="utf-8"))
    rows = payload.get("rows", [])
    out_dir = Path(args.out_dir) if Path(args.out_dir).is_absolute() else REPO_ROOT / args.out_dir
    measured = payload.get("measured")
    if isinstance(measured, list):
        try:
            from wildctrl.reporting.figures import write_figures

            metric = args.metric or "accuracy"
            written = write_figures(
                measured,
                out_dir,
                metric=metric,
                group_by=args.group_by,
                formats=tuple(args.formats),
                dpi=args.dpi,
            )
            for path in written.values():
                print(f"wrote {path} via wildctrl.reporting.figures")
            return 0
        except Exception as exc:  # noqa: BLE001 - fall back to local renderer
            print(f"note: library figure writer unavailable ({exc}); using script fallback")

    available = sorted({name for row in rows for name in row.get("metrics", {})})
    metric = args.metric or (available[0] if available else "metric")
    if args.metric and available and args.metric not in available:
        print(f"metric {args.metric!r} is not present; available metrics are {available}")
        return 2

    grouped = group_values(rows, args.group_by, metric)
    stats = summarize(grouped)

    out_dir.mkdir(parents=True, exist_ok=True)

    figure = render(stats, grouped, metric, args)
    written = []
    for suffix in args.formats:
        path = out_dir / f"{args.name}.{suffix}"
        figure.savefig(path, dpi=args.dpi)
        written.append(path)
    figure.clf()

    caption = write_caption(out_dir / f"{args.name}.caption.txt", metric, stats)
    for path in [*written, caption]:
        print(f"wrote {path}")
    if not stats:
        print("\nNote: the figure is a labelled placeholder. Nothing has been measured yet.")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
